# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f03b575b7a55b818bc282a69bd0a760e064172de438b5479c2444dac7cb2e837f99769d02a07cec343e34393daccff53aa909bf31751ada5199cf3d44e3b15ff

test:
  secret_key_base: 31d6d96addc8498f5dba7672752d6e725fcf9171436a71491cffb0a057b62406b910f4b9af91892754844c85c32e82c9c25eb9ebe67fad056de38033ca3c8d97

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
